workflows:
  build-android:
    name: Build Flutter Android APK
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      android: latest
      vars:
        PACKAGE_NAME: "com.example.sync_browsers"
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build APK (release)
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - youremail@example.com
